name = "MyProject"
uuid = "3f6c6753-b97b-4739-9a92-98fd5546d0b8"
authors = ["levijacobhughes <levijhughes@icloud.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
